---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - variables/vars-rds-automation-with-sm.yaml

  tasks:
  - name: Get RDS credentials from Secrets Manager
    community.aws.aws_secret:
      name: webapp_database_credential
    register: secrets

  - name: Set variables from retrieved secrets
    set_fact:
      db_username: "{{ secrets.SecretString | from_json | default({}).username }}"
      db_password: "{{ secrets.SecretString | from_json | default({}).password }}"

  - name                   : Create DB instance with added AWS KMS Encryption Enabled
    rds_instance           :
      id                   : "{{ db_identifier }}"
      state                : "{{ db_state }}"
      region               : "{{ db_region }}"
      engine               : "{{ db_engine }}"
      username             : "{{ db_username }}"
      password             : "{{ db_password }}"
      db_instance_class    : "{{ db_instance_class }}"
      allocated_storage    : "{{ db_allocated_storage }}"
      storage_encrypted    : true
      skip_final_snapshot  : true
